/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tp_maquina_is2.Interfaces.Paneles.Estudiante;

import com.mycompany.tp_maquina_is2.Logica.Excepciones.ManagementException;
import com.mycompany.tp_maquina_is2.Logica.Managers.ExamenManager;
import com.mycompany.tp_maquina_is2.Logica.Managers.PlanEstudiosManager;
import com.mycompany.tp_maquina_is2.Logica.Transferencia.Examen;
import com.mycompany.tp_maquina_is2.Logica.Transferencia.Experiencia;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juan_
 */
public class ABMExpPanel extends javax.swing.JPanel {

    private int nroRegistro;
    private int caso;
    private String codPlan;

    /**
     * Creates new form AgregarExpPanel
     */
    public ABMExpPanel(int nroRegistro,String codPlan) {
        this.nroRegistro = nroRegistro;
        this.codPlan=codPlan;
        initComponents();
        TablaExamenes.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        TablaExamenes.getTableHeader().setOpaque(true);
        TablaExamenes.getTableHeader().setBackground(new Color(58,56,56));
        TablaExamenes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.getViewport().setBackground(new Color(33, 33, 33)); //tabla color negro
        TablaExamenes.setBackground(new Color(58,56,56));//coloresrow
        TablaExamenes.getTableHeader().setForeground(Color.white);
        this.PanelDatosExp.setVisible(false);
        BorrarL.setVisible(false);
        caso=1;
        LlenarTablaExamenesSinExp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        panelExamRendidos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaExamenes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BorrarL = new javax.swing.JLabel();
        agregarexpLabel = new javax.swing.JLabel();
        eliminarExpLabel = new javax.swing.JLabel();
        modificarExpLabel = new javax.swing.JLabel();
        PanelDatosExp = new javax.swing.JPanel();
        SliderDif = new javax.swing.JSlider();
        SliderDedi = new javax.swing.JSlider();
        DificultadL = new javax.swing.JLabel();
        DificultadL1 = new javax.swing.JLabel();
        DificultadL2 = new javax.swing.JLabel();
        ConfirmarDatosExp = new javax.swing.JButton();
        Datos = new javax.swing.JLabel();
        DatosDed = new javax.swing.JLabel();
        DiasDeEstudio = new javax.swing.JTextField();

        Contenedor.setBackground(new java.awt.Color(33, 33, 33));
        Contenedor.setPreferredSize(new java.awt.Dimension(920, 500));

        panelExamRendidos.setBackground(new java.awt.Color(33, 33, 33));
        panelExamRendidos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaExamenes.setBackground(new java.awt.Color(33, 33, 33));
        TablaExamenes.setForeground(new java.awt.Color(255, 255, 255));
        TablaExamenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaExamenes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TablaExamenes.setFocusable(false);
        TablaExamenes.setRowHeight(25);
        TablaExamenes.setSelectionBackground(new java.awt.Color(118, 35, 47));
        TablaExamenes.setSelectionForeground(new java.awt.Color(255, 255, 255));
        TablaExamenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaExamenesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaExamenes);

        panelExamRendidos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 390, 319));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lista de Exámenes");
        panelExamRendidos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        BorrarL.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        BorrarL.setForeground(new java.awt.Color(255, 255, 255));
        BorrarL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_info_20px.png"))); // NOI18N
        BorrarL.setText("Si selecciona una fila, borrara esa experiencia de examen.");
        panelExamRendidos.add(BorrarL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        agregarexpLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        agregarexpLabel.setForeground(new java.awt.Color(255, 255, 255));
        agregarexpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_add_to_inbox_50px.png"))); // NOI18N
        agregarexpLabel.setText("AGREGAR");
        agregarexpLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarexpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarexpLabelMouseClicked(evt);
            }
        });
        panelExamRendidos.add(agregarexpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 140, -1));

        eliminarExpLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        eliminarExpLabel.setForeground(new java.awt.Color(255, 255, 255));
        eliminarExpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_remove_from_inbox_50px.png"))); // NOI18N
        eliminarExpLabel.setText("ELIMINAR");
        eliminarExpLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarExpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarExpLabelMouseClicked(evt);
            }
        });
        panelExamRendidos.add(eliminarExpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 130, -1));

        modificarExpLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        modificarExpLabel.setForeground(new java.awt.Color(255, 255, 255));
        modificarExpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_refresh_50px.png"))); // NOI18N
        modificarExpLabel.setText("MODIFICAR");
        modificarExpLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificarExpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarExpLabelMouseClicked(evt);
            }
        });
        panelExamRendidos.add(modificarExpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 140, -1));

        PanelDatosExp.setBackground(new java.awt.Color(33, 33, 33));
        PanelDatosExp.setForeground(new java.awt.Color(255, 255, 255));
        PanelDatosExp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SliderDif.setMaximum(10);
        SliderDif.setValue(5);
        SliderDif.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SliderDif.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderDifStateChanged(evt);
            }
        });
        PanelDatosExp.add(SliderDif, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, 28));

        SliderDedi.setMaximum(10);
        SliderDedi.setValue(5);
        SliderDedi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SliderDedi.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderDediStateChanged(evt);
            }
        });
        PanelDatosExp.add(SliderDedi, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 190, -1));

        DificultadL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DificultadL.setForeground(new java.awt.Color(255, 255, 255));
        DificultadL.setText("Dificultad:");
        PanelDatosExp.add(DificultadL, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        DificultadL1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DificultadL1.setForeground(new java.awt.Color(255, 255, 255));
        DificultadL1.setText("Días de Estudio:");
        PanelDatosExp.add(DificultadL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        DificultadL2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DificultadL2.setForeground(new java.awt.Color(255, 255, 255));
        DificultadL2.setText("Dedicación:");
        PanelDatosExp.add(DificultadL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        ConfirmarDatosExp.setBackground(new java.awt.Color(102, 255, 102));
        ConfirmarDatosExp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ConfirmarDatosExp.setForeground(new java.awt.Color(51, 51, 51));
        ConfirmarDatosExp.setText("ACEPTAR");
        ConfirmarDatosExp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ConfirmarDatosExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarDatosExpActionPerformed(evt);
            }
        });
        PanelDatosExp.add(ConfirmarDatosExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 200, 32));

        Datos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Datos.setForeground(new java.awt.Color(255, 255, 255));
        Datos.setPreferredSize(new java.awt.Dimension(20, 10));
        PanelDatosExp.add(Datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 30, 26));

        DatosDed.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DatosDed.setForeground(new java.awt.Color(255, 255, 255));
        DatosDed.setPreferredSize(new java.awt.Dimension(20, 15));
        PanelDatosExp.add(DatosDed, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 30, 26));

        DiasDeEstudio.setToolTipText("Cantidad de días estudiados");
        DiasDeEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiasDeEstudioActionPerformed(evt);
            }
        });
        PanelDatosExp.add(DiasDeEstudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 180, -1));

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addComponent(panelExamRendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDatosExp, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE))
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelExamRendidos, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
            .addComponent(PanelDatosExp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean validarDatos(){
        try {
            int diasEstudio = Integer.parseInt(DiasDeEstudio.getText().trim());
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            return false;
        }
        return true;
    }
    
    private void ConfirmarDatosExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarDatosExpActionPerformed
        if(validarDatos()){
            Experiencia experiencia=new Experiencia(SliderDif.getValue(),Integer.parseInt(DiasDeEstudio.getText().trim()), SliderDedi.getValue(), (String) TablaExamenes.getValueAt(TablaExamenes.getSelectedRow(), 0));
            try{
            if(caso==1){
                
                ExamenManager.crearExperiencia(experiencia);
                JOptionPane.showMessageDialog(null, "Experiencia cargada exitosamente!.");
                LlenarTablaExamenesSinExp();
            }else{
                ExamenManager.ModificarExperiencia((String)TablaExamenes.getValueAt(TablaExamenes.getSelectedRow(), 0),experiencia);
                JOptionPane.showMessageDialog(null, "Experiencia modificada exitosamente!.");
                LlenarTablaExamenesConExp();
            }}catch(ManagementException ex){
                    JOptionPane.showMessageDialog(null, ex.getMessage());}
            SliderDedi.setValue(5);
            SliderDif.setValue(5);
            DiasDeEstudio.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Datos Invalidos!");}
    }//GEN-LAST:event_ConfirmarDatosExpActionPerformed

    private void SliderDifStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderDifStateChanged
        Datos.setText(String.valueOf(SliderDif.getValue()));
    }//GEN-LAST:event_SliderDifStateChanged

    private void SliderDediStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderDediStateChanged
        DatosDed.setText(String.valueOf(SliderDedi.getValue()));
    }//GEN-LAST:event_SliderDediStateChanged

    private void DiasDeEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiasDeEstudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiasDeEstudioActionPerformed

    private void TablaExamenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaExamenesMouseClicked
        if(caso==1 || caso==3){
            PanelDatosExp.setVisible(true);
        }else{
        switch (JOptionPane.showConfirmDialog(this, "Esta seguro de que desea borrar la experiencia (nombre: "
                + TablaExamenes.getValueAt(TablaExamenes.getSelectedRow(), 1) + "),\n se borrara toda la informacion"
                + "relacionada al mismo")) {
        case JOptionPane.OK_OPTION:
        String codExamen = (String) TablaExamenes.getValueAt(TablaExamenes.getSelectedRow(), 0);
        try{
        ExamenManager.EliminarExperiencia(codExamen);
        JOptionPane.showMessageDialog(null, "Experiencia eliminada exitosamente!.");
        DefaultTableModel modelo = (DefaultTableModel)TablaExamenes.getModel();
        modelo.removeRow(TablaExamenes.getSelectedRow());
        TablaExamenes.setModel(modelo);
        }catch (ManagementException | HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        break;
        }
        }
    }//GEN-LAST:event_TablaExamenesMouseClicked

    private void modificarExpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarExpLabelMouseClicked
        LlenarTablaExamenesConExp();
        BorrarL.setVisible(false);
        caso=3;
    }//GEN-LAST:event_modificarExpLabelMouseClicked

    private void eliminarExpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarExpLabelMouseClicked
        PanelDatosExp.setVisible(false);
        BorrarL.setVisible(true);
        LlenarTablaExamenesConExp();
        caso=2;
    }//GEN-LAST:event_eliminarExpLabelMouseClicked

    private void agregarexpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarexpLabelMouseClicked
        LlenarTablaExamenesSinExp();
        BorrarL.setVisible(false);
        caso=1;
    }//GEN-LAST:event_agregarexpLabelMouseClicked

    public void LlenarTablaExamenesSinExp() {
        try {
            ArrayList<Examen> examenes = ExamenManager.examenesEstudianteSinExp(nroRegistro,codPlan);
            DefaultTableModel modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }};
            modelo.setRowCount(0);
            modelo.addColumn("Codigo Examen");
            modelo.addColumn("Nombre Materia");
            modelo.addColumn("Fecha Examen");
            for (Examen examen : examenes) {
                String[]datos = examen.getCodHistoriaAcademica().split("-");
                modelo.addRow(new Object[]{examen.getCodigo(),
                    PlanEstudiosManager.buscarMateria(examen.getCodMateria(), datos[1]).getNombre(),
                        examen.getFecha().toString()});
            }
            TablaExamenes.setModel(modelo);
        } catch (ManagementException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

        public void LlenarTablaExamenesConExp() {
        try {
            ArrayList<Examen> examenes = ExamenManager.examenesEstudianteConExp(nroRegistro,codPlan);
            DefaultTableModel modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }};
            modelo.setRowCount(0);
            modelo.addColumn("Codigo");
            modelo.addColumn("Nombre");
            modelo.addColumn("Fecha");
            modelo.addColumn("Dificultad");
            modelo.addColumn("Dias de estudio");
            modelo.addColumn("Dedicacion");
            for (Examen examen : examenes) {
                    String[]datos = examen.getCodHistoriaAcademica().split("-");
                    modelo.addRow(new Object[]{examen.getCodigo(),
                        PlanEstudiosManager.buscarMateria(examen.getCodMateria(), datos[1]).getNombre(),
                        examen.getFecha().toString(),examen.getExperiencia().getDificultad(),examen.getExperiencia().getDias(),examen.getExperiencia().getDedicacion()});
            }
            TablaExamenes.setModel(modelo);
        } catch (ManagementException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BorrarL;
    private javax.swing.JButton ConfirmarDatosExp;
    private javax.swing.JPanel Contenedor;
    private javax.swing.JLabel Datos;
    private javax.swing.JLabel DatosDed;
    private javax.swing.JTextField DiasDeEstudio;
    private javax.swing.JLabel DificultadL;
    private javax.swing.JLabel DificultadL1;
    private javax.swing.JLabel DificultadL2;
    private javax.swing.JPanel PanelDatosExp;
    private javax.swing.JSlider SliderDedi;
    private javax.swing.JSlider SliderDif;
    private javax.swing.JTable TablaExamenes;
    private javax.swing.JLabel agregarexpLabel;
    private javax.swing.JLabel eliminarExpLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel modificarExpLabel;
    private javax.swing.JPanel panelExamRendidos;
    // End of variables declaration//GEN-END:variables
}
