/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tp_maquina_is2.Interfaces.Paneles.Estudiante;

import com.mycompany.tp_maquina_is2.Logica.Excepciones.ManagementException;
import com.mycompany.tp_maquina_is2.Logica.Managers.ExamenManager;
import com.mycompany.tp_maquina_is2.Logica.Managers.PlanEstudiosManager;
import com.mycompany.tp_maquina_is2.Logica.Transferencia.Examen;
import com.mycompany.tp_maquina_is2.Logica.Transferencia.Experiencia;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juan_
 */
public class AgregarExpPanel extends javax.swing.JPanel {

    private int nroRegistro;

    /**
     * Creates new form AgregarExpPanel
     */
    public AgregarExpPanel(int nroRegistro) {
        this.nroRegistro = nroRegistro;
        initComponents();
        TablaExamenes.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        TablaExamenes.getTableHeader().setOpaque(true);
        TablaExamenes.getTableHeader().setBackground(new Color(0, 153, 153));
        TablaExamenes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.getViewport().setBackground(new Color(255, 255, 255)); //tabla color blanc
        this.PanelDatosExp.setVisible(false);
        LlenarTablaExamenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        panelExamRendidos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaExamenes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        PanelDatosExp = new javax.swing.JPanel();
        SliderDif = new javax.swing.JSlider();
        SliderDedi = new javax.swing.JSlider();
        DificultadL = new javax.swing.JLabel();
        DificultadL1 = new javax.swing.JLabel();
        DificultadL2 = new javax.swing.JLabel();
        ConfirmarDatosExp = new javax.swing.JButton();
        Datos = new javax.swing.JLabel();
        DatosDed = new javax.swing.JLabel();
        DiasDeEstudio = new javax.swing.JTextField();

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));
        Contenedor.setPreferredSize(new java.awt.Dimension(920, 500));

        panelExamRendidos.setBackground(new java.awt.Color(255, 255, 255));

        TablaExamenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "FECHA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaExamenes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TablaExamenes.setFocusable(false);
        TablaExamenes.setRowHeight(25);
        TablaExamenes.setSelectionBackground(new java.awt.Color(118, 35, 47));
        TablaExamenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaExamenesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaExamenes);
        if (TablaExamenes.getColumnModel().getColumnCount() > 0) {
            TablaExamenes.getColumnModel().getColumn(0).setResizable(false);
            TablaExamenes.getColumnModel().getColumn(1).setResizable(false);
            TablaExamenes.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Lista de Examenes");

        javax.swing.GroupLayout panelExamRendidosLayout = new javax.swing.GroupLayout(panelExamRendidos);
        panelExamRendidos.setLayout(panelExamRendidosLayout);
        panelExamRendidosLayout.setHorizontalGroup(
            panelExamRendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExamRendidosLayout.createSequentialGroup()
                .addGroup(panelExamRendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelExamRendidosLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelExamRendidosLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelExamRendidosLayout.setVerticalGroup(
            panelExamRendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExamRendidosLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        PanelDatosExp.setBackground(new java.awt.Color(255, 255, 255));

        SliderDif.setMaximum(10);
        SliderDif.setValue(5);
        SliderDif.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SliderDif.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderDifStateChanged(evt);
            }
        });

        SliderDedi.setMaximum(10);
        SliderDedi.setValue(5);
        SliderDedi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SliderDedi.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderDediStateChanged(evt);
            }
        });

        DificultadL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DificultadL.setText("Dificultad:");

        DificultadL1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DificultadL1.setText("Días de Estudio:");

        DificultadL2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DificultadL2.setText("Dedicación:");

        ConfirmarDatosExp.setBackground(new java.awt.Color(102, 255, 102));
        ConfirmarDatosExp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ConfirmarDatosExp.setText("Confirmar Experiencia");
        ConfirmarDatosExp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ConfirmarDatosExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarDatosExpActionPerformed(evt);
            }
        });

        Datos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Datos.setPreferredSize(new java.awt.Dimension(20, 10));

        DatosDed.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DatosDed.setPreferredSize(new java.awt.Dimension(20, 15));

        DiasDeEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiasDeEstudioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDatosExpLayout = new javax.swing.GroupLayout(PanelDatosExp);
        PanelDatosExp.setLayout(PanelDatosExpLayout);
        PanelDatosExpLayout.setHorizontalGroup(
            PanelDatosExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosExpLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(PanelDatosExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosExpLayout.createSequentialGroup()
                        .addGroup(PanelDatosExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DificultadL, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DificultadL1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DificultadL2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(PanelDatosExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDatosExpLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelDatosExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SliderDedi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SliderDif, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ConfirmarDatosExp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(PanelDatosExpLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(DiasDeEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosExpLayout.createSequentialGroup()
                        .addComponent(DatosDed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosExpLayout.createSequentialGroup()
                        .addComponent(Datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203))))
        );
        PanelDatosExpLayout.setVerticalGroup(
            PanelDatosExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosExpLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(PanelDatosExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DificultadL)
                    .addComponent(SliderDif, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Datos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDatosExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DiasDeEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DificultadL1))
                .addGap(37, 37, 37)
                .addGroup(PanelDatosExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DificultadL2)
                    .addComponent(SliderDedi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DatosDed, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ConfirmarDatosExp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addComponent(panelExamRendidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDatosExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelExamRendidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelDatosExp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmarDatosExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarDatosExpActionPerformed
        int diasEstudio = 0;
        try {
            diasEstudio = Integer.parseInt(DiasDeEstudio.getText().trim());
            int dificultad = SliderDif.getValue();
            int dedicacion = SliderDedi.getValue();
            String codExamen = (String) TablaExamenes.getValueAt(TablaExamenes.getSelectedRow(), 0);
            ExamenManager.agregarExperiencia(new Experiencia(dificultad, diasEstudio, dedicacion, codExamen));
            JOptionPane.showMessageDialog(null, "Experiencia cargada exitosamente!.");
            LlenarTablaExamenes();

        } catch (ManagementException | HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_ConfirmarDatosExpActionPerformed

    private void SliderDifStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderDifStateChanged
        Datos.setText(String.valueOf(SliderDif.getValue()));
    }//GEN-LAST:event_SliderDifStateChanged

    private void SliderDediStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderDediStateChanged
        DatosDed.setText(String.valueOf(SliderDedi.getValue()));
    }//GEN-LAST:event_SliderDediStateChanged

    private void DiasDeEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiasDeEstudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiasDeEstudioActionPerformed

    private void TablaExamenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaExamenesMouseClicked
        PanelDatosExp.setVisible(true);
    }//GEN-LAST:event_TablaExamenesMouseClicked

    public void LlenarTablaExamenes() {
        try {
            ArrayList<Examen> examenes = ExamenManager.examenesEstudiante(nroRegistro);
            DefaultTableModel modelo = (DefaultTableModel) TablaExamenes.getModel();
            //modelo.setRowCount(0);
            Object[] lista = new Object[40];
            for (Examen examen : examenes) {
                if (examen.getExperiencia() == null) {
                    String[]datos = examen.getCodHistoriaAcademica().split("-");
                    
                    modelo.addRow(new Object[]{examen.getCodigo(),
                        PlanEstudiosManager.buscarMateria(examen.getCodMateria(), datos[1]).getNombre(),
                        examen.getFecha().toString()});
                }
            }
        } catch (ManagementException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmarDatosExp;
    private javax.swing.JPanel Contenedor;
    private javax.swing.JLabel Datos;
    private javax.swing.JLabel DatosDed;
    private javax.swing.JTextField DiasDeEstudio;
    private javax.swing.JLabel DificultadL;
    private javax.swing.JLabel DificultadL1;
    private javax.swing.JLabel DificultadL2;
    private javax.swing.JPanel PanelDatosExp;
    private javax.swing.JSlider SliderDedi;
    private javax.swing.JSlider SliderDif;
    private javax.swing.JTable TablaExamenes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelExamRendidos;
    // End of variables declaration//GEN-END:variables
}
