/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tp_maquina_is2.Interfaces.Paneles.Estudiante;

import com.mycompany.tp_maquina_is2.Datos.Conexion;
import com.mycompany.tp_maquina_is2.Logica.Excepciones.ManagementException;
import com.mycompany.tp_maquina_is2.Logica.Managers.EstudianteManager;
import com.mycompany.tp_maquina_is2.Logica.Managers.ExamenManager;
import com.mycompany.tp_maquina_is2.Logica.Managers.HistoriaAcademicaManager;
import com.mycompany.tp_maquina_is2.Logica.Managers.PlanEstudiosManager;
import com.mycompany.tp_maquina_is2.Logica.Transferencia.Estudiante;
import com.mycompany.tp_maquina_is2.Logica.Util.ArchivosManager;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ivanb
 */
public class InicioEstudiante extends javax.swing.JPanel {

    private Estudiante user;
    private String codPlan;

    /**
     * Creates new form Inicio
     */
    public InicioEstudiante(Estudiante user, String codPlan) {
        this.user = user;
        this.codPlan = codPlan;
        
        initComponents();
        changePane(new PanelFondoInicio());

        try {
            Conexion conn = Conexion.getInstance();

            // Inicializacion de Managers
            ExamenManager.init(conn);
            EstudianteManager.init(conn);
            HistoriaAcademicaManager.init(conn);
            PlanEstudiosManager.init(conn);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Ha habido un problema conectando a la Base de Datos");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Archivo = new javax.swing.JFileChooser();
        MenuTop = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelinicio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        añadirExpLabel = new javax.swing.JLabel();
        verListaLabel = new javax.swing.JLabel();
        cargarHistoriaLabel = new javax.swing.JLabel();
        jLabelnavbarfondo = new javax.swing.JLabel();
        Cambiable = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuTop.setBackground(new java.awt.Color(204, 204, 204));
        MenuTop.setToolTipText("");
        MenuTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MenuTopMouseDragged(evt);
            }
        });
        MenuTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuTopMousePressed(evt);
            }
        });
        MenuTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_account_40px.png"))); // NOI18N
        jLabel2.setText("Cuenta");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuTop.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 20, 120, 50));

        labelinicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelinicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelinicioMouseClicked(evt);
            }
        });
        MenuTop.add(labelinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 260, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_automatic_40px.png"))); // NOI18N
        jLabel1.setText("Configuración");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuTop.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 120, 50));

        añadirExpLabel.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        añadirExpLabel.setForeground(new java.awt.Color(51, 51, 51));
        añadirExpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_talk_40px.png"))); // NOI18N
        añadirExpLabel.setText("Experiencia");
        añadirExpLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        añadirExpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                añadirExpLabelMouseClicked(evt);
            }
        });
        MenuTop.add(añadirExpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 120, 50));

        verListaLabel.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        verListaLabel.setForeground(new java.awt.Color(51, 51, 51));
        verListaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_shortlist_40px.png"))); // NOI18N
        verListaLabel.setText("Lista finales");
        verListaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verListaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verListaLabelMouseClicked(evt);
            }
        });
        MenuTop.add(verListaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 120, 50));

        cargarHistoriaLabel.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        cargarHistoriaLabel.setForeground(new java.awt.Color(51, 51, 51));
        cargarHistoriaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_xls_import_40px.png"))); // NOI18N
        cargarHistoriaLabel.setText("Cargar Historia");
        cargarHistoriaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cargarHistoriaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargarHistoriaLabelMouseClicked(evt);
            }
        });
        MenuTop.add(cargarHistoriaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 120, 50));

        jLabelnavbarfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/navbar1200x115.jpg"))); // NOI18N
        MenuTop.add(jLabelnavbarfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 90));

        add(MenuTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 90));

        Cambiable.setBackground(new java.awt.Color(255, 255, 255));
        Cambiable.setPreferredSize(new java.awt.Dimension(950, 500));
        Cambiable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(Cambiable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, 1200, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void changePane(JPanel jPanel) {
        Cambiable.setLayout(new java.awt.CardLayout());
        Cambiable.removeAll();
        Cambiable.add(jPanel);
        Cambiable.revalidate();
        Cambiable.repaint();
    }
    
    private void MenuTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuTopMouseDragged

    }//GEN-LAST:event_MenuTopMouseDragged

    private void MenuTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuTopMousePressed

    }//GEN-LAST:event_MenuTopMousePressed

    private void cargarHistoriaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarHistoriaLabelMouseClicked
        int returnVal = Archivo.showOpenDialog(this);
        if (returnVal == Archivo.APPROVE_OPTION) {
            File file = Archivo.getSelectedFile();
            try {
                ArchivosManager.cargarHistoriaAcademica(user.getNroRegistro(),this.codPlan, file);

                JOptionPane.showMessageDialog(null, "Historia cargada correctamente");
            } catch (ManagementException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } else {
        }
    }//GEN-LAST:event_cargarHistoriaLabelMouseClicked

    private void verListaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verListaLabelMouseClicked
        changePane(new ListaPanel(user.getNroRegistro(), codPlan));
    }//GEN-LAST:event_verListaLabelMouseClicked

    private void añadirExpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadirExpLabelMouseClicked
        changePane(new ABMExpPanel(user.getNroRegistro()));
    }//GEN-LAST:event_añadirExpLabelMouseClicked

    private void labelinicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelinicioMouseClicked
        changePane(new PanelFondoInicio());
    }//GEN-LAST:event_labelinicioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser Archivo;
    private javax.swing.JPanel Cambiable;
    private javax.swing.JPanel MenuTop;
    private javax.swing.JLabel añadirExpLabel;
    private javax.swing.JLabel cargarHistoriaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelnavbarfondo;
    private javax.swing.JLabel labelinicio;
    private javax.swing.JLabel verListaLabel;
    // End of variables declaration//GEN-END:variables
}
