/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tp_maquina_is2.Interfaces.Paneles.Estudiante;

import com.mycompany.tp_maquina_is2.Datos.Conexion;
import com.mycompany.tp_maquina_is2.Logica.Excepciones.ManagementException;
import com.mycompany.tp_maquina_is2.Logica.Managers.EstudianteManager;
import com.mycompany.tp_maquina_is2.Logica.Managers.ExamenManager;
import com.mycompany.tp_maquina_is2.Logica.Managers.HistoriaAcademicaManager;
import com.mycompany.tp_maquina_is2.Logica.Managers.PlanEstudiosManager;
import com.mycompany.tp_maquina_is2.Logica.Transferencia.Estudiante;
import com.mycompany.tp_maquina_is2.Logica.Util.ArchivosManager;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ivanb
 */
public class InicioEstudiante extends javax.swing.JPanel {
    Color DefaultColor,ClickedColor;
    private Estudiante user;
    private String codPlan;
    

    /**
     * Creates new form Inicio
     */
    public InicioEstudiante(Estudiante user, String codPlan) {
        this.user = user;
        this.codPlan = codPlan;
        initComponents();
        DefaultColor=new Color(41,40,40);
        ClickedColor=new Color(58,56,56);
        changePane(new PanelFondoInicio());

        try {
            Conexion conn = Conexion.getInstance();

            // Inicializacion de Managers
            ExamenManager.init(conn);
            EstudianteManager.init(conn);
            HistoriaAcademicaManager.init(conn);
            PlanEstudiosManager.init(conn);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Ha habido un problema conectando a la Base de Datos");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Archivo = new javax.swing.JFileChooser();
        MenuTop = new javax.swing.JPanel();
        labelinicio = new javax.swing.JLabel();
        menu1 = new javax.swing.JPanel();
        cargarHistoriaLabel = new javax.swing.JLabel();
        menu2 = new javax.swing.JPanel();
        verListaLabel = new javax.swing.JLabel();
        menu3 = new javax.swing.JPanel();
        añadirExpLabel = new javax.swing.JLabel();
        menu4 = new javax.swing.JPanel();
        configlabel = new javax.swing.JLabel();
        Cambiable = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuTop.setBackground(new java.awt.Color(41, 40, 40));
        MenuTop.setToolTipText("");
        MenuTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MenuTopMouseDragged(evt);
            }
        });
        MenuTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuTopMousePressed(evt);
            }
        });
        MenuTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelinicio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelinicio.setForeground(new java.awt.Color(255, 255, 255));
        labelinicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo fcfmyn.png"))); // NOI18N
        labelinicio.setText("FCFMyN");
        labelinicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelinicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelinicioMouseClicked(evt);
            }
        });
        MenuTop.add(labelinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 70));

        menu1.setBackground(new java.awt.Color(41, 40, 40));
        menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu1MouseExited(evt);
            }
        });

        cargarHistoriaLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cargarHistoriaLabel.setForeground(new java.awt.Color(255, 255, 255));
        cargarHistoriaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_xls_import_40px_1.png"))); // NOI18N
        cargarHistoriaLabel.setText("CARGAR HISTORIA");
        cargarHistoriaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cargarHistoriaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargarHistoriaLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cargarHistoriaLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cargarHistoriaLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menu1Layout = new javax.swing.GroupLayout(menu1);
        menu1.setLayout(menu1Layout);
        menu1Layout.setHorizontalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cargarHistoriaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        menu1Layout.setVerticalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cargarHistoriaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        MenuTop.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 160, 70));

        menu2.setBackground(new java.awt.Color(41, 40, 40));
        menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu2MouseEntered(evt);
            }
        });

        verListaLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        verListaLabel.setForeground(new java.awt.Color(255, 255, 255));
        verListaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_shortlist_40px_1.png"))); // NOI18N
        verListaLabel.setText("LISTA FINALES");
        verListaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verListaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verListaLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verListaLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verListaLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menu2Layout = new javax.swing.GroupLayout(menu2);
        menu2.setLayout(menu2Layout);
        menu2Layout.setHorizontalGroup(
            menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(verListaLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        menu2Layout.setVerticalGroup(
            menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(verListaLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        MenuTop.add(menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 150, 70));

        menu3.setBackground(new java.awt.Color(41, 40, 40));

        añadirExpLabel.setBackground(new java.awt.Color(41, 40, 40));
        añadirExpLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        añadirExpLabel.setForeground(new java.awt.Color(255, 255, 255));
        añadirExpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_talk_40px_1.png"))); // NOI18N
        añadirExpLabel.setText("  EXPERIENCIA");
        añadirExpLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        añadirExpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                añadirExpLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                añadirExpLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                añadirExpLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menu3Layout = new javax.swing.GroupLayout(menu3);
        menu3.setLayout(menu3Layout);
        menu3Layout.setHorizontalGroup(
            menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(añadirExpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        menu3Layout.setVerticalGroup(
            menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(añadirExpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        MenuTop.add(menu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 150, 70));

        menu4.setBackground(new java.awt.Color(41, 40, 40));

        configlabel.setBackground(new java.awt.Color(41, 40, 40));
        configlabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        configlabel.setForeground(new java.awt.Color(255, 255, 255));
        configlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_automatic_40px_2.png"))); // NOI18N
        configlabel.setText("CONFIGURACIÓN");
        configlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        configlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                configlabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                configlabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menu4Layout = new javax.swing.GroupLayout(menu4);
        menu4.setLayout(menu4Layout);
        menu4Layout.setHorizontalGroup(
            menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu4Layout.createSequentialGroup()
                .addComponent(configlabel)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        menu4Layout.setVerticalGroup(
            menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(configlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        MenuTop.add(menu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 150, 70));

        add(MenuTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 70));

        Cambiable.setBackground(new java.awt.Color(255, 255, 255));
        Cambiable.setPreferredSize(new java.awt.Dimension(950, 500));
        Cambiable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(Cambiable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1200, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void changePane(JPanel jPanel) {
        Cambiable.setLayout(new java.awt.CardLayout());
        Cambiable.removeAll();
        Cambiable.add(jPanel);
        Cambiable.revalidate();
        Cambiable.repaint();
    }
    
    private void MenuTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuTopMouseDragged

    }//GEN-LAST:event_MenuTopMouseDragged

    private void MenuTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuTopMousePressed

    }//GEN-LAST:event_MenuTopMousePressed

    private void cargarHistoriaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarHistoriaLabelMouseClicked
        int returnVal = Archivo.showOpenDialog(this);
        if (returnVal == Archivo.APPROVE_OPTION) {
            File file = Archivo.getSelectedFile();
            try {
                ArchivosManager.cargarHistoriaAcademica(user.getNroRegistro(),this.codPlan, file);

                JOptionPane.showMessageDialog(null, "Historia cargada correctamente");
            } catch (ManagementException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } else {
        }
    }//GEN-LAST:event_cargarHistoriaLabelMouseClicked

    private void verListaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verListaLabelMouseClicked
        changePane(new ListaPanel(user.getNroRegistro(), codPlan));
    }//GEN-LAST:event_verListaLabelMouseClicked

    private void añadirExpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadirExpLabelMouseClicked
        changePane(new ABMExpPanel(user.getNroRegistro(),codPlan));
    }//GEN-LAST:event_añadirExpLabelMouseClicked

    private void labelinicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelinicioMouseClicked
        changePane(new PanelFondoInicio());
    }//GEN-LAST:event_labelinicioMouseClicked

    private void menu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseEntered

        
    }//GEN-LAST:event_menu1MouseEntered

    private void menu2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu2MouseEntered
    
    }//GEN-LAST:event_menu2MouseEntered

    private void menu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseExited
        
        
    }//GEN-LAST:event_menu1MouseExited

    private void cargarHistoriaLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarHistoriaLabelMouseEntered
        menu1.setBackground(ClickedColor);
    }//GEN-LAST:event_cargarHistoriaLabelMouseEntered

    private void cargarHistoriaLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarHistoriaLabelMouseExited
       menu1.setBackground(DefaultColor);
    }//GEN-LAST:event_cargarHistoriaLabelMouseExited

    private void verListaLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verListaLabelMouseEntered
        menu2.setBackground(ClickedColor);
    }//GEN-LAST:event_verListaLabelMouseEntered

    private void verListaLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verListaLabelMouseExited
        menu2.setBackground(DefaultColor);
    }//GEN-LAST:event_verListaLabelMouseExited

    private void añadirExpLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadirExpLabelMouseEntered
        menu3.setBackground(ClickedColor);
    }//GEN-LAST:event_añadirExpLabelMouseEntered

    private void añadirExpLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadirExpLabelMouseExited
        menu3.setBackground(DefaultColor);
    }//GEN-LAST:event_añadirExpLabelMouseExited

    private void configlabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configlabelMouseEntered
        menu4.setBackground(ClickedColor);
    }//GEN-LAST:event_configlabelMouseEntered

    private void configlabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configlabelMouseExited
        menu4.setBackground(DefaultColor);
    }//GEN-LAST:event_configlabelMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser Archivo;
    private javax.swing.JPanel Cambiable;
    private javax.swing.JPanel MenuTop;
    private javax.swing.JLabel añadirExpLabel;
    private javax.swing.JLabel cargarHistoriaLabel;
    private javax.swing.JLabel configlabel;
    private javax.swing.JLabel labelinicio;
    private javax.swing.JPanel menu1;
    private javax.swing.JPanel menu2;
    private javax.swing.JPanel menu3;
    private javax.swing.JPanel menu4;
    private javax.swing.JLabel verListaLabel;
    // End of variables declaration//GEN-END:variables
}
