/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tp_maquina_is2.Interfaces.Paneles.Estudiante;

import com.mycompany.tp_maquina_is2.Logica.Excepciones.ManagementException;
import com.mycompany.tp_maquina_is2.Logica.Managers.HistoriaAcademicaManager;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juan_
 */
public class ListaPanel extends javax.swing.JPanel {

    private int nroRegistro;
    private String codPlanEstudios;

    /**
     * Creates new form ListaPanel
     */
    public ListaPanel(int nroRegistro, String codPlanEstudios) {
        this.nroRegistro = nroRegistro;
        this.codPlanEstudios = codPlanEstudios;
        initComponents();
        TablaMaterias.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        TablaMaterias.getTableHeader().setOpaque(true);
        TablaMaterias.getTableHeader().setBackground(new Color(0, 153, 153));
        jScrollPane1.getViewport().setBackground(new Color(255, 255, 255)); //tabla color blanco
        TablaMaterias.getTableHeader().setReorderingAllowed(false);
        //doy aceptar
        ActionEvent evt = null;
        jButton1ActionPerformed(evt);

        textfieldias.setVisible(false);
        labeldias.setVisible(false);

        Inscripcion.setVisible(false);
        Inscripcion1.setVisible(false);
        mesa.setVisible(false);
        Estadisticas.setVisible(false);

    }

    public void listaFinales(int dias) {
        String criterio = ComboBoxCriterio.getSelectedItem().toString();
        DefaultTableModel modelo = (DefaultTableModel) TablaMaterias.getModel();
        modelo.setRowCount(0);
        try {
            switch (criterio) {
                case "Correlativas":
                    TablaMaterias.getTableHeader().getColumnModel().getColumn(2).setHeaderValue("CORRELATIVAS");
                    break;
                case "Dificultad":
                    TablaMaterias.getTableHeader().getColumnModel().getColumn(2).setHeaderValue("DIFICULTAD PROMEDIO");
                    break;
                case "Tiempo":
                    if (dias != 0) {
                        try {
                            dias = Integer.parseInt(textfieldias.getText().trim());
                        } catch (HeadlessException | NumberFormatException e) {
                            JOptionPane.showMessageDialog(null, e.getMessage());
                        }
                        
                        TablaMaterias.getTableHeader().getColumnModel().getColumn(2).setHeaderValue("APROBARON EN " + dias + " DIAS O MENOS");
                    }
                    break;

                case "Vencimiento":
                    TablaMaterias.getTableHeader().getColumnModel().getColumn(2).setHeaderValue("SE VENCE EN: (SEMANAS)");
            }
            TablaMaterias.getTableHeader().repaint();

            ArrayList<Object[]> filasTabla = HistoriaAcademicaManager.listaExamenes(nroRegistro, codPlanEstudios, criterio, dias);

            for (Object[] objects : filasTabla) {
                modelo.addRow(objects);
            }
        } catch (ManagementException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCambiable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMaterias = new javax.swing.JTable();
        ComboBoxCriterio = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textfieldias = new javax.swing.JTextField();
        labeldias = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Inscripcion = new javax.swing.JPanel();
        estudianteBL = new javax.swing.JLabel();
        Inscripcion1 = new javax.swing.JPanel();
        estudianteBL1 = new javax.swing.JLabel();
        mesa = new javax.swing.JLabel();
        Estadisticas = new javax.swing.JPanel();
        estudianteBL2 = new javax.swing.JLabel();

        PanelCambiable.setBackground(new java.awt.Color(255, 255, 255));
        PanelCambiable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "CORRELATIVAS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaMaterias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TablaMaterias.setFocusable(false);
        TablaMaterias.setRowHeight(25);
        TablaMaterias.setSelectionBackground(new java.awt.Color(118, 35, 47));
        TablaMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMateriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaMaterias);
        if (TablaMaterias.getColumnModel().getColumnCount() > 0) {
            TablaMaterias.getColumnModel().getColumn(0).setResizable(false);
            TablaMaterias.getColumnModel().getColumn(1).setResizable(false);
            TablaMaterias.getColumnModel().getColumn(2).setResizable(false);
        }

        PanelCambiable.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 670, 340));

        ComboBoxCriterio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboBoxCriterio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Correlativas", "Tiempo", "Vencimiento", "Dificultad" }));
        ComboBoxCriterio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ComboBoxCriterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCriterioActionPerformed(evt);
            }
        });
        PanelCambiable.add(ComboBoxCriterio, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 170, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("A continuación se muestran las materias que el Estudiante está en condiciones de rendir, es decir, cumple con las correlativas ");
        PanelCambiable.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("El criterio seleccionado por default es la cantidad de materias que tienen a dicha materia como correlativa.");
        PanelCambiable.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        textfieldias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldiasActionPerformed(evt);
            }
        });
        PanelCambiable.add(textfieldias, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 170, -1));

        labeldias.setForeground(new java.awt.Color(51, 51, 51));
        labeldias.setText("Dias para estudiar:");
        PanelCambiable.add(labeldias, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, -1, -1));

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PanelCambiable.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 160, 20));

        Inscripcion.setBackground(new java.awt.Color(118, 35, 47));
        Inscripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Inscripcion.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Inscripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InscripcionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InscripcionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InscripcionMouseExited(evt);
            }
        });

        estudianteBL.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        estudianteBL.setForeground(new java.awt.Color(255, 255, 255));
        estudianteBL.setText("Inscribirse a examen");
        estudianteBL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout InscripcionLayout = new javax.swing.GroupLayout(Inscripcion);
        Inscripcion.setLayout(InscripcionLayout);
        InscripcionLayout.setHorizontalGroup(
            InscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InscripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(estudianteBL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InscripcionLayout.setVerticalGroup(
            InscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InscripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(estudianteBL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelCambiable.add(Inscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, -1, -1));

        Inscripcion1.setBackground(new java.awt.Color(118, 35, 47));
        Inscripcion1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Inscripcion1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Inscripcion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inscripcion1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Inscripcion1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Inscripcion1MouseExited(evt);
            }
        });

        estudianteBL1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        estudianteBL1.setForeground(new java.awt.Color(255, 255, 255));
        estudianteBL1.setText("Ver Lista Inscriptos");
        estudianteBL1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout Inscripcion1Layout = new javax.swing.GroupLayout(Inscripcion1);
        Inscripcion1.setLayout(Inscripcion1Layout);
        Inscripcion1Layout.setHorizontalGroup(
            Inscripcion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inscripcion1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(estudianteBL1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Inscripcion1Layout.setVerticalGroup(
            Inscripcion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inscripcion1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(estudianteBL1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelCambiable.add(Inscripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, -1, -1));

        mesa.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        mesa.setText("Se corresponden a la mesa siguiente : Diciembre");
        PanelCambiable.add(mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 340, -1));

        Estadisticas.setBackground(new java.awt.Color(118, 35, 47));
        Estadisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Estadisticas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Estadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstadisticasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EstadisticasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EstadisticasMouseExited(evt);
            }
        });

        estudianteBL2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        estudianteBL2.setForeground(new java.awt.Color(255, 255, 255));
        estudianteBL2.setText("Ver Estadisticas");
        estudianteBL2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout EstadisticasLayout = new javax.swing.GroupLayout(Estadisticas);
        Estadisticas.setLayout(EstadisticasLayout);
        EstadisticasLayout.setHorizontalGroup(
            EstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstadisticasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(estudianteBL2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EstadisticasLayout.setVerticalGroup(
            EstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstadisticasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(estudianteBL2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelCambiable.add(Estadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PanelCambiable, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PanelCambiable, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void changePane(JPanel jPanel) {
        PanelCambiable.setLayout(new java.awt.CardLayout());
        PanelCambiable.removeAll();
        PanelCambiable.add(jPanel);
        PanelCambiable.revalidate();
        PanelCambiable.repaint();
    }

    private void ComboBoxCriterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCriterioActionPerformed
        if (ComboBoxCriterio.getSelectedItem().toString().equals("Tiempo")) {
            labeldias.setVisible(true);
            textfieldias.setVisible(true);
        } else {
            labeldias.setVisible(false);
            textfieldias.setVisible(false);
        }

    }//GEN-LAST:event_ComboBoxCriterioActionPerformed

    private void textfieldiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldiasActionPerformed

    }//GEN-LAST:event_textfieldiasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int dias = 0;
        if (ComboBoxCriterio.getSelectedItem().toString().equals("Tiempo")) {
            try {
                dias = Integer.parseInt(textfieldias.getText().trim());
            } catch (HeadlessException | NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Debes ingresar la cantidad de días que tenés para estudiar");
            }
        }
        this.listaFinales(dias);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void TablaMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMateriasMouseClicked
        Inscripcion.setVisible(true);
        Inscripcion1.setVisible(true);
        mesa.setVisible(true);
        Estadisticas.setVisible(true);

    }//GEN-LAST:event_TablaMateriasMouseClicked

    private void InscripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InscripcionMouseClicked
        changePane(new InscripcionPanel(nroRegistro, codPlanEstudios, (String) TablaMaterias.getValueAt(TablaMaterias.getSelectedRow(), 0), false));
    }//GEN-LAST:event_InscripcionMouseClicked

    private void InscripcionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InscripcionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_InscripcionMouseEntered

    private void InscripcionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InscripcionMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_InscripcionMouseExited

    private void Inscripcion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inscripcion1MouseClicked
        changePane(new InscripcionPanel(nroRegistro, codPlanEstudios, (String) TablaMaterias.getValueAt(TablaMaterias.getSelectedRow(), 0), true));
    }//GEN-LAST:event_Inscripcion1MouseClicked

    private void Inscripcion1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inscripcion1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Inscripcion1MouseEntered

    private void Inscripcion1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inscripcion1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Inscripcion1MouseExited

    private void EstadisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstadisticasMouseClicked
       changePane(new EstadisticasEstudiante((String) TablaMaterias.getValueAt(TablaMaterias.getSelectedRow(), 0),codPlanEstudios));

    }//GEN-LAST:event_EstadisticasMouseClicked

    private void EstadisticasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstadisticasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadisticasMouseEntered

    private void EstadisticasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstadisticasMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadisticasMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxCriterio;
    private javax.swing.JPanel Estadisticas;
    private javax.swing.JPanel Inscripcion;
    private javax.swing.JPanel Inscripcion1;
    private javax.swing.JPanel PanelCambiable;
    private javax.swing.JTable TablaMaterias;
    private javax.swing.JLabel estudianteBL;
    private javax.swing.JLabel estudianteBL1;
    private javax.swing.JLabel estudianteBL2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labeldias;
    private javax.swing.JLabel mesa;
    private javax.swing.JTextField textfieldias;
    // End of variables declaration//GEN-END:variables
}
