/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tp_maquina_is2.Interfaces.Paneles;

import com.mycompany.tp_maquina_is2.Logica.Transferencia.Examen;
import com.mycompany.tp_maquina_is2.Logica.Transferencia.Materia;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juan_
 */
public class AgregarExpPanel extends javax.swing.JPanel {

    /**
     * Creates new form AgregarExpPanel
     */
    public AgregarExpPanel(ArrayList<Examen> examenes,HashMap<Integer,Materia> materias) {
        initComponents();
        this.PanelDatosExp.setVisible(false);
        //LlenarTablaExamenes(examenes,materias);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        panelExamRendidos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaExamenes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ElegirExam = new javax.swing.JButton();
        PanelDatosExp = new javax.swing.JPanel();
        SliderDif = new javax.swing.JSlider();
        SliderDedi = new javax.swing.JSlider();
        SpinnerDiasDeEstudio = new javax.swing.JSpinner();
        DificultadL = new javax.swing.JLabel();
        DificultadL1 = new javax.swing.JLabel();
        DificultadL2 = new javax.swing.JLabel();
        ConfirmarDatosExp = new javax.swing.JButton();
        Datos = new javax.swing.JLabel();

        TablaExamenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Codigo", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaExamenes);
        if (TablaExamenes.getColumnModel().getColumnCount() > 0) {
            TablaExamenes.getColumnModel().getColumn(0).setResizable(false);
            TablaExamenes.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Examenes Rendidos");

        ElegirExam.setBackground(new java.awt.Color(102, 255, 102));
        ElegirExam.setText("Elegir examen");
        ElegirExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElegirExamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelExamRendidosLayout = new javax.swing.GroupLayout(panelExamRendidos);
        panelExamRendidos.setLayout(panelExamRendidosLayout);
        panelExamRendidosLayout.setHorizontalGroup(
            panelExamRendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExamRendidosLayout.createSequentialGroup()
                .addGroup(panelExamRendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelExamRendidosLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panelExamRendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelExamRendidosLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelExamRendidosLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(ElegirExam, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelExamRendidosLayout.setVerticalGroup(
            panelExamRendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExamRendidosLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(ElegirExam, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        SliderDif.setMaximum(10);
        SliderDif.setValue(5);
        SliderDif.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderDifStateChanged(evt);
            }
        });

        SliderDedi.setMaximum(10);
        SliderDedi.setValue(5);

        DificultadL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DificultadL.setText("Dificultad");

        DificultadL1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DificultadL1.setText("Dias de Estudio");

        DificultadL2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DificultadL2.setText("Dedicacion");

        ConfirmarDatosExp.setBackground(new java.awt.Color(102, 255, 102));
        ConfirmarDatosExp.setText("Confirmar Experiencia");
        ConfirmarDatosExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarDatosExpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDatosExpLayout = new javax.swing.GroupLayout(PanelDatosExp);
        PanelDatosExp.setLayout(PanelDatosExpLayout);
        PanelDatosExpLayout.setHorizontalGroup(
            PanelDatosExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosExpLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(PanelDatosExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosExpLayout.createSequentialGroup()
                        .addGroup(PanelDatosExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DificultadL2)
                            .addComponent(DificultadL1)
                            .addComponent(SliderDedi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SliderDif, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SpinnerDiasDeEstudio)
                            .addComponent(DificultadL)
                            .addComponent(ConfirmarDatosExp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosExpLayout.createSequentialGroup()
                        .addComponent(Datos)
                        .addGap(198, 198, 198))))
        );
        PanelDatosExpLayout.setVerticalGroup(
            PanelDatosExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosExpLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(DificultadL)
                .addGap(7, 7, 7)
                .addComponent(Datos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SliderDif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(DificultadL1)
                .addGap(18, 18, 18)
                .addComponent(SpinnerDiasDeEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(DificultadL2)
                .addGap(27, 27, 27)
                .addComponent(SliderDedi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(ConfirmarDatosExp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addComponent(panelExamRendidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDatosExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelExamRendidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelDatosExp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmarDatosExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarDatosExpActionPerformed
      try{
            Integer DiasDeEstudio=Integer.parseInt((String)SpinnerDiasDeEstudio.getValue());
        }catch(Exception e){
               JOptionPane.showMessageDialog(null, "Error en los dias de estudio");
                }
            int Dificultad=SliderDif.getValue();
            int Dedicacion=SliderDedi.getValue();
            int cod_examen = (Integer)TablaExamenes.getValueAt(TablaExamenes.getSelectedRow(),0);
            
        //metodo manager para crear exp(cod_examen,DiasDeEstudio,Dificultad,Dedicacion);
    }//GEN-LAST:event_ConfirmarDatosExpActionPerformed

    private void ElegirExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElegirExamActionPerformed
        if(TablaExamenes.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "No se selecciono ningun examen");
        }
        else
        this.PanelDatosExp.setVisible(true);
    }//GEN-LAST:event_ElegirExamActionPerformed

    private void SliderDifStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderDifStateChanged
        Datos.setText(String.valueOf(SliderDif.getValue()));
    }//GEN-LAST:event_SliderDifStateChanged

    public void LlenarTablaExamenes(ArrayList<Examen> array,HashMap<Integer,Materia> arrayM){
        DefaultTableModel modelo = (DefaultTableModel) TablaExamenes.getModel();
        Object [] lista=new Object[40];
        for(Examen e : array)
        
        modelo.addRow(new Object []{e.getCodMateria(),arrayM.get(e.getCodMateria()).getNombre()});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmarDatosExp;
    private javax.swing.JPanel Contenedor;
    private javax.swing.JLabel Datos;
    private javax.swing.JLabel DificultadL;
    private javax.swing.JLabel DificultadL1;
    private javax.swing.JLabel DificultadL2;
    private javax.swing.JButton ElegirExam;
    private javax.swing.JPanel PanelDatosExp;
    private javax.swing.JSlider SliderDedi;
    private javax.swing.JSlider SliderDif;
    private javax.swing.JSpinner SpinnerDiasDeEstudio;
    private javax.swing.JTable TablaExamenes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelExamRendidos;
    // End of variables declaration//GEN-END:variables
}
