/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tp_maquina_is2.Interfaces.Paneles;

import com.mycompany.tp_maquina_is2.Logica.Managers.ExamenManager;
import com.mycompany.tp_maquina_is2.Logica.Transferencia.Examen;
import com.mycompany.tp_maquina_is2.Logica.Transferencia.Materia;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juan_
 */
public class AgregarExpPanel extends javax.swing.JPanel {

    /**
     * Creates new form AgregarExpPanel
     */
    public AgregarExpPanel() {
        initComponents();
        this.PanelDatosExp.setVisible(false);
        //LlenarTablaExamenes(examenes,materias);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        panelExamRendidos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaExamenes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        PanelDatosExp = new javax.swing.JPanel();
        SliderDif = new javax.swing.JSlider();
        SliderDedi = new javax.swing.JSlider();
        DificultadL = new javax.swing.JLabel();
        DificultadL1 = new javax.swing.JLabel();
        DificultadL2 = new javax.swing.JLabel();
        ConfirmarDatosExp = new javax.swing.JButton();
        Datos = new javax.swing.JLabel();
        DatosDed = new javax.swing.JLabel();
        DiasDeEstudio = new javax.swing.JTextField();

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));
        Contenedor.setPreferredSize(new java.awt.Dimension(920, 500));

        panelExamRendidos.setBackground(new java.awt.Color(255, 255, 255));

        TablaExamenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaExamenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaExamenesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaExamenes);
        if (TablaExamenes.getColumnModel().getColumnCount() > 0) {
            TablaExamenes.getColumnModel().getColumn(0).setResizable(false);
            TablaExamenes.getColumnModel().getColumn(1).setResizable(false);
            TablaExamenes.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Lista de Examenes");

        javax.swing.GroupLayout panelExamRendidosLayout = new javax.swing.GroupLayout(panelExamRendidos);
        panelExamRendidos.setLayout(panelExamRendidosLayout);
        panelExamRendidosLayout.setHorizontalGroup(
            panelExamRendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExamRendidosLayout.createSequentialGroup()
                .addGroup(panelExamRendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelExamRendidosLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelExamRendidosLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelExamRendidosLayout.setVerticalGroup(
            panelExamRendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExamRendidosLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelDatosExp.setBackground(new java.awt.Color(255, 255, 255));

        SliderDif.setMaximum(10);
        SliderDif.setValue(5);
        SliderDif.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderDifStateChanged(evt);
            }
        });

        SliderDedi.setMaximum(10);
        SliderDedi.setValue(5);
        SliderDedi.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderDediStateChanged(evt);
            }
        });

        DificultadL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DificultadL.setText("Dificultad");

        DificultadL1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DificultadL1.setText("Dias de Estudio");

        DificultadL2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DificultadL2.setText("Dedicacion");

        ConfirmarDatosExp.setBackground(new java.awt.Color(102, 255, 102));
        ConfirmarDatosExp.setText("Confirmar Experiencia");
        ConfirmarDatosExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarDatosExpActionPerformed(evt);
            }
        });

        Datos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Datos.setPreferredSize(new java.awt.Dimension(20, 10));

        DatosDed.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DatosDed.setPreferredSize(new java.awt.Dimension(20, 15));

        DiasDeEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiasDeEstudioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDatosExpLayout = new javax.swing.GroupLayout(PanelDatosExp);
        PanelDatosExp.setLayout(PanelDatosExpLayout);
        PanelDatosExpLayout.setHorizontalGroup(
            PanelDatosExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosExpLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(PanelDatosExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosExpLayout.createSequentialGroup()
                        .addGroup(PanelDatosExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DificultadL1)
                            .addComponent(SliderDedi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SliderDif, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DificultadL)
                            .addComponent(ConfirmarDatosExp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DificultadL2)
                            .addComponent(DiasDeEstudio))
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosExpLayout.createSequentialGroup()
                        .addComponent(Datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosExpLayout.createSequentialGroup()
                        .addComponent(DatosDed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205))))
        );
        PanelDatosExpLayout.setVerticalGroup(
            PanelDatosExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosExpLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(DificultadL)
                .addGap(28, 28, 28)
                .addComponent(SliderDif, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Datos, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DificultadL1)
                .addGap(27, 27, 27)
                .addComponent(DiasDeEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DificultadL2)
                .addGap(23, 23, 23)
                .addComponent(SliderDedi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DatosDed, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ConfirmarDatosExp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addComponent(panelExamRendidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDatosExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelExamRendidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelDatosExp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmarDatosExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarDatosExpActionPerformed
      try{
            Integer DiasDeEstudioo=Integer.parseInt(DiasDeEstudio.getText().trim());
        }catch(Exception e){
               JOptionPane.showMessageDialog(null, "Error en los dias de estudio");
                }
            int Dificultad=SliderDif.getValue();
            int Dedicacion=SliderDedi.getValue();
            int cod_examen = (Integer)TablaExamenes.getValueAt(TablaExamenes.getSelectedRow(),0);
            
        
        //metodo manager para crear exp(cod_examen,DiasDeEstudio,Dificultad,Dedicacion);
    }//GEN-LAST:event_ConfirmarDatosExpActionPerformed

    private void SliderDifStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderDifStateChanged
        Datos.setText(String.valueOf(SliderDif.getValue()));
    }//GEN-LAST:event_SliderDifStateChanged

    private void SliderDediStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderDediStateChanged
       DatosDed.setText(String.valueOf(SliderDedi.getValue()));
    }//GEN-LAST:event_SliderDediStateChanged

    private void DiasDeEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiasDeEstudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiasDeEstudioActionPerformed

    private void TablaExamenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaExamenesMouseClicked
       PanelDatosExp.setVisible(true);
    }//GEN-LAST:event_TablaExamenesMouseClicked

        //ArrayList<Examen> examenes,HashMap<Integer,Materia> materias
    public void LlenarTablaExamenes(){
        //Hashmap<String,Examen> aux=ExamenManager.examenesEstudiante(codigo_historia_academica);
        DefaultTableModel modelo = (DefaultTableModel) TablaExamenes.getModel();
        Object [] lista=new Object[40];
        //for(Examen e : //aux)
        {
         //modelo.addRow(new Object []{e.getCodMateria(),arrayM.get(e.getCodMateria()).getNombre()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmarDatosExp;
    private javax.swing.JPanel Contenedor;
    private javax.swing.JLabel Datos;
    private javax.swing.JLabel DatosDed;
    private javax.swing.JTextField DiasDeEstudio;
    private javax.swing.JLabel DificultadL;
    private javax.swing.JLabel DificultadL1;
    private javax.swing.JLabel DificultadL2;
    private javax.swing.JPanel PanelDatosExp;
    private javax.swing.JSlider SliderDedi;
    private javax.swing.JSlider SliderDif;
    private javax.swing.JTable TablaExamenes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelExamRendidos;
    // End of variables declaration//GEN-END:variables
}
