/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tp_maquina_is2.Interfaces.Paneles.NoDocente;

/**
 *
 * @author ivanb
 */
public class EstadisticasNoDocente extends javax.swing.JPanel {

    /**
     * Creates new form EstadisticasNoDocente
     */
    public EstadisticasNoDocente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        SeleccionP = new javax.swing.JPanel();
        dificultadPromedioP = new javax.swing.JPanel();
        dificultadPromedioL = new javax.swing.JLabel();
        preparacionP = new javax.swing.JPanel();
        preparacionL = new javax.swing.JLabel();
        dedicacionP = new javax.swing.JPanel();
        dedicacionL = new javax.swing.JLabel();
        mesasP = new javax.swing.JPanel();
        mesasL = new javax.swing.JLabel();
        labelSeleccion = new javax.swing.JLabel();
        labelTop10 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedor.setBackground(new java.awt.Color(255, 255, 255));
        contenedor.setLayout(new java.awt.CardLayout());
        add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 620, 560));

        SeleccionP.setBackground(new java.awt.Color(118, 35, 47));

        dificultadPromedioP.setBackground(new java.awt.Color(118, 35, 47));
        dificultadPromedioP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dificultadPromedioP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        dificultadPromedioP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dificultadPromedioPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dificultadPromedioPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dificultadPromedioPMouseExited(evt);
            }
        });

        dificultadPromedioL.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        dificultadPromedioL.setForeground(new java.awt.Color(255, 255, 255));
        dificultadPromedioL.setText("Dificultad promedio");
        dificultadPromedioL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout dificultadPromedioPLayout = new javax.swing.GroupLayout(dificultadPromedioP);
        dificultadPromedioP.setLayout(dificultadPromedioPLayout);
        dificultadPromedioPLayout.setHorizontalGroup(
            dificultadPromedioPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dificultadPromedioPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dificultadPromedioL)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        dificultadPromedioPLayout.setVerticalGroup(
            dificultadPromedioPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dificultadPromedioPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dificultadPromedioL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        preparacionP.setBackground(new java.awt.Color(118, 35, 47));
        preparacionP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        preparacionP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        preparacionP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                preparacionPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                preparacionPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                preparacionPMouseExited(evt);
            }
        });

        preparacionL.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        preparacionL.setForeground(new java.awt.Color(255, 255, 255));
        preparacionL.setText("Tiempo promedio de preparacion");
        preparacionL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout preparacionPLayout = new javax.swing.GroupLayout(preparacionP);
        preparacionP.setLayout(preparacionPLayout);
        preparacionPLayout.setHorizontalGroup(
            preparacionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preparacionPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(preparacionL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        preparacionPLayout.setVerticalGroup(
            preparacionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preparacionPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(preparacionL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dedicacionP.setBackground(new java.awt.Color(118, 35, 47));
        dedicacionP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dedicacionP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        dedicacionP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dedicacionPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dedicacionPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dedicacionPMouseExited(evt);
            }
        });

        dedicacionL.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        dedicacionL.setForeground(new java.awt.Color(255, 255, 255));
        dedicacionL.setText("Dedicacion promedio");
        dedicacionL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout dedicacionPLayout = new javax.swing.GroupLayout(dedicacionP);
        dedicacionP.setLayout(dedicacionPLayout);
        dedicacionPLayout.setHorizontalGroup(
            dedicacionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dedicacionPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dedicacionL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dedicacionPLayout.setVerticalGroup(
            dedicacionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dedicacionPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dedicacionL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mesasP.setBackground(new java.awt.Color(118, 35, 47));
        mesasP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mesasP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        mesasP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesasPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mesasPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mesasPMouseExited(evt);
            }
        });

        mesasL.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mesasL.setForeground(new java.awt.Color(255, 255, 255));
        mesasL.setText("Mesas mas rendidas");
        mesasL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout mesasPLayout = new javax.swing.GroupLayout(mesasP);
        mesasP.setLayout(mesasPLayout);
        mesasPLayout.setHorizontalGroup(
            mesasPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mesasPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mesasL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mesasPLayout.setVerticalGroup(
            mesasPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mesasPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mesasL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelSeleccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelSeleccion.setText("Seleccione una Estadistica");

        labelTop10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTop10.setText("Top 10");

        javax.swing.GroupLayout SeleccionPLayout = new javax.swing.GroupLayout(SeleccionP);
        SeleccionP.setLayout(SeleccionPLayout);
        SeleccionPLayout.setHorizontalGroup(
            SeleccionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeleccionPLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(SeleccionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSeleccion)
                    .addComponent(labelTop10)
                    .addComponent(mesasP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SeleccionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(preparacionP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dedicacionP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dificultadPromedioP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        SeleccionPLayout.setVerticalGroup(
            SeleccionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeleccionPLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelSeleccion)
                .addGap(68, 68, 68)
                .addComponent(labelTop10)
                .addGap(30, 30, 30)
                .addComponent(dificultadPromedioP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(preparacionP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dedicacionP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mesasP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        add(SeleccionP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void dificultadPromedioPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dificultadPromedioPMouseClicked
    }//GEN-LAST:event_dificultadPromedioPMouseClicked

    private void dificultadPromedioPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dificultadPromedioPMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dificultadPromedioPMouseEntered

    private void dificultadPromedioPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dificultadPromedioPMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dificultadPromedioPMouseExited

    private void preparacionPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preparacionPMouseClicked
    }//GEN-LAST:event_preparacionPMouseClicked

    private void preparacionPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preparacionPMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_preparacionPMouseEntered

    private void preparacionPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preparacionPMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_preparacionPMouseExited

    private void dedicacionPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dedicacionPMouseClicked
    }//GEN-LAST:event_dedicacionPMouseClicked

    private void dedicacionPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dedicacionPMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dedicacionPMouseEntered

    private void dedicacionPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dedicacionPMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dedicacionPMouseExited

    private void mesasPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesasPMouseClicked
    }//GEN-LAST:event_mesasPMouseClicked

    private void mesasPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesasPMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_mesasPMouseEntered

    private void mesasPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesasPMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_mesasPMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SeleccionP;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel dedicacionL;
    private javax.swing.JPanel dedicacionP;
    private javax.swing.JLabel dificultadPromedioL;
    private javax.swing.JPanel dificultadPromedioP;
    private javax.swing.JLabel labelSeleccion;
    private javax.swing.JLabel labelTop10;
    private javax.swing.JLabel mesasL;
    private javax.swing.JPanel mesasP;
    private javax.swing.JLabel preparacionL;
    private javax.swing.JPanel preparacionP;
    // End of variables declaration//GEN-END:variables
}
