/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tp_maquina_is2.Interfaces.Paneles.NoDocente;

import javax.swing.JOptionPane;

/**
 *
 * @author ivanb
 */
public class InicioNoDocente extends javax.swing.JPanel {

    /**
     * Creates new form InicioNoDocente
     */
    public InicioNoDocente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cambiable = new javax.swing.JPanel();
        PrincipalL = new javax.swing.JLabel();
        PrincipalL1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MenuTop = new javax.swing.JPanel();
        insertButtonP = new javax.swing.JPanel();
        insertButtonL = new javax.swing.JLabel();
        tablesButtonP = new javax.swing.JPanel();
        tablesButtonL = new javax.swing.JLabel();

        Cambiable.setBackground(new java.awt.Color(255, 255, 255));
        Cambiable.setPreferredSize(new java.awt.Dimension(950, 500));
        Cambiable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PrincipalL.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        PrincipalL.setText("Bienvenido al sistema de asistencia universitaria");
        Cambiable.add(PrincipalL, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 60, -1, 37));

        PrincipalL1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        PrincipalL1.setText("Seleccione la operacion que desee realizar");
        Cambiable.add(PrincipalL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 103, 419, 45));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/tp_maquina_is2/Interfaces/logo_imagen.png"))); // NOI18N
        Cambiable.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 154, 475, 291));

        MenuTop.setBackground(new java.awt.Color(118, 35, 47));
        MenuTop.setToolTipText("");
        MenuTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MenuTopMouseDragged(evt);
            }
        });
        MenuTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuTopMousePressed(evt);
            }
        });
        MenuTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insertButtonP.setBackground(new java.awt.Color(118, 35, 47));
        insertButtonP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        insertButtonP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        insertButtonP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertButtonPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                insertButtonPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                insertButtonPMouseExited(evt);
            }
        });

        insertButtonL.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        insertButtonL.setForeground(new java.awt.Color(255, 255, 255));
        insertButtonL.setText("Planes de Estudios");
        insertButtonL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout insertButtonPLayout = new javax.swing.GroupLayout(insertButtonP);
        insertButtonP.setLayout(insertButtonPLayout);
        insertButtonPLayout.setHorizontalGroup(
            insertButtonPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertButtonPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insertButtonL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        insertButtonPLayout.setVerticalGroup(
            insertButtonPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertButtonPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insertButtonL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MenuTop.add(insertButtonP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 170, -1));

        tablesButtonP.setBackground(new java.awt.Color(118, 35, 47));
        tablesButtonP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablesButtonP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tablesButtonP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablesButtonPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tablesButtonPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tablesButtonPMouseExited(evt);
            }
        });

        tablesButtonL.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tablesButtonL.setForeground(new java.awt.Color(255, 255, 255));
        tablesButtonL.setText("Estadisticas");
        tablesButtonL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout tablesButtonPLayout = new javax.swing.GroupLayout(tablesButtonP);
        tablesButtonP.setLayout(tablesButtonPLayout);
        tablesButtonPLayout.setHorizontalGroup(
            tablesButtonPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablesButtonPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablesButtonL)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        tablesButtonPLayout.setVerticalGroup(
            tablesButtonPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablesButtonPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablesButtonL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MenuTop.add(tablesButtonP, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MenuTop, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Cambiable, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MenuTop, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(2, 2, 2)
                    .addComponent(Cambiable, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void insertButtonPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertButtonPMouseClicked
        JOptionPane.showMessageDialog(null, "En construccion");
    }//GEN-LAST:event_insertButtonPMouseClicked

    private void insertButtonPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertButtonPMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_insertButtonPMouseEntered

    private void insertButtonPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertButtonPMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_insertButtonPMouseExited

    private void tablesButtonPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablesButtonPMouseClicked
        JOptionPane.showMessageDialog(null, "En construccion");
    }//GEN-LAST:event_tablesButtonPMouseClicked

    private void tablesButtonPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablesButtonPMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tablesButtonPMouseEntered

    private void tablesButtonPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablesButtonPMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tablesButtonPMouseExited

    private void MenuTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuTopMouseDragged

    }//GEN-LAST:event_MenuTopMouseDragged

    private void MenuTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuTopMousePressed

    }//GEN-LAST:event_MenuTopMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cambiable;
    private javax.swing.JPanel MenuTop;
    private javax.swing.JLabel PrincipalL;
    private javax.swing.JLabel PrincipalL1;
    private javax.swing.JLabel insertButtonL;
    private javax.swing.JPanel insertButtonP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel tablesButtonL;
    private javax.swing.JPanel tablesButtonP;
    // End of variables declaration//GEN-END:variables
}
