/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tp_maquina_is2.Interfaces.Paneles.NoDocente.ABMPlanDeEstudios;

import com.mycompany.tp_maquina_is2.Logica.Excepciones.ManagementException;
import com.mycompany.tp_maquina_is2.Logica.Managers.PlanEstudiosManager;
import com.mycompany.tp_maquina_is2.Logica.Transferencia.Materia;
import com.mycompany.tp_maquina_is2.Logica.Transferencia.PlanEstudios;
import java.awt.Color;
import java.util.HashMap;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ivanb
 */
public class ModificarPlan extends javax.swing.JPanel {

    private String codPlanEstudios;
    private Color activo;
    private Color inactivo;

    /**
     * Creates new form ModificarPlan
     */
    public ModificarPlan(String codPlanEstudios) {
        initComponents();

        this.codPlanEstudios = codPlanEstudios;
        
        this.activo = new Color(51, 51, 51);
        this.inactivo = new Color(165, 165, 165);

        codigoTF.setText(codPlanEstudios);
        try {
            propuestaTF.setText(PlanEstudiosManager.buscar(codPlanEstudios).getPropuesta());
        } catch (ManagementException e) {
        }

        sepCodigo.setVisible(false);
        sepPropuesta.setVisible(false);

        llenarTablaMaterias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        PrincipalL = new javax.swing.JLabel();
        materiaP = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCorrelativas = new javax.swing.JTable();
        PrincipalL3 = new javax.swing.JLabel();
        PrincipalL4 = new javax.swing.JLabel();
        codigoMateriaTF = new javax.swing.JTextField();
        PrincipalL5 = new javax.swing.JLabel();
        modificarMateriaBP = new javax.swing.JPanel();
        modificarMateriaBL = new javax.swing.JLabel();
        sepNombre = new javax.swing.JSeparator();
        sepCodigoMateria = new javax.swing.JSeparator();
        nombreTF = new javax.swing.JTextField();
        PrincipalL1 = new javax.swing.JLabel();
        PrincipalL2 = new javax.swing.JLabel();
        propuestaTF = new javax.swing.JTextField();
        sepPropuesta = new javax.swing.JSeparator();
        sepCodigo = new javax.swing.JSeparator();
        codigoTF = new javax.swing.JTextField();
        modificarBP = new javax.swing.JPanel();
        modificarBL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMaterias = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedor.setBackground(new java.awt.Color(255, 255, 255));
        contenedor.setPreferredSize(new java.awt.Dimension(950, 500));
        contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PrincipalL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PrincipalL.setForeground(new java.awt.Color(165, 165, 165));
        PrincipalL.setText("Propuesta:");
        contenedor.add(PrincipalL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 30));

        materiaP.setBackground(new java.awt.Color(255, 255, 255));
        materiaP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCorrelativas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCorrelativas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaCorrelativas.setFocusable(false);
        tablaCorrelativas.setRowHeight(25);
        tablaCorrelativas.setSelectionBackground(new java.awt.Color(118, 35, 47));
        tablaCorrelativas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCorrelativasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCorrelativas);
        if (tablaCorrelativas.getColumnModel().getColumnCount() > 0) {
            tablaCorrelativas.getColumnModel().getColumn(0).setResizable(false);
            tablaCorrelativas.getColumnModel().getColumn(1).setResizable(false);
        }

        materiaP.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 320, 200));

        PrincipalL3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PrincipalL3.setForeground(new java.awt.Color(165, 165, 165));
        PrincipalL3.setText("Seleccione una materia para eliminarla");
        materiaP.add(PrincipalL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, 37));

        PrincipalL4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PrincipalL4.setForeground(new java.awt.Color(165, 165, 165));
        PrincipalL4.setText("Nombre:");
        materiaP.add(PrincipalL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, 30));

        codigoMateriaTF.setBackground(new java.awt.Color(255, 255, 255));
        codigoMateriaTF.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        codigoMateriaTF.setForeground(new java.awt.Color(165, 165, 165));
        codigoMateriaTF.setBorder(null);
        codigoMateriaTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codigoMateriaTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigoMateriaTFFocusLost(evt);
            }
        });
        codigoMateriaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoMateriaTFActionPerformed(evt);
            }
        });
        materiaP.add(codigoMateriaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 290, 30));

        PrincipalL5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PrincipalL5.setForeground(new java.awt.Color(165, 165, 165));
        PrincipalL5.setText("Codigo:");
        materiaP.add(PrincipalL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 30));

        modificarMateriaBP.setBackground(new java.awt.Color(118, 35, 47));
        modificarMateriaBP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modificarMateriaBP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        modificarMateriaBP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarMateriaBPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificarMateriaBPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificarMateriaBPMouseExited(evt);
            }
        });

        modificarMateriaBL.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        modificarMateriaBL.setForeground(new java.awt.Color(255, 255, 255));
        modificarMateriaBL.setText("Modificar");
        modificarMateriaBL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout modificarMateriaBPLayout = new javax.swing.GroupLayout(modificarMateriaBP);
        modificarMateriaBP.setLayout(modificarMateriaBPLayout);
        modificarMateriaBPLayout.setHorizontalGroup(
            modificarMateriaBPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarMateriaBPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modificarMateriaBL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        modificarMateriaBPLayout.setVerticalGroup(
            modificarMateriaBPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarMateriaBPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modificarMateriaBL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        materiaP.add(modificarMateriaBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 90, -1));
        materiaP.add(sepNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 290, -1));
        materiaP.add(sepCodigoMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 290, -1));

        nombreTF.setBackground(new java.awt.Color(255, 255, 255));
        nombreTF.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        nombreTF.setForeground(new java.awt.Color(165, 165, 165));
        nombreTF.setBorder(null);
        nombreTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreTFFocusLost(evt);
            }
        });
        nombreTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTFActionPerformed(evt);
            }
        });
        materiaP.add(nombreTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 290, 30));

        contenedor.add(materiaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 470, 560));

        PrincipalL1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PrincipalL1.setForeground(new java.awt.Color(165, 165, 165));
        PrincipalL1.setText("Seleccione si desea modificar una materia");
        contenedor.add(PrincipalL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 37));

        PrincipalL2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PrincipalL2.setForeground(new java.awt.Color(165, 165, 165));
        PrincipalL2.setText("Codigo:");
        contenedor.add(PrincipalL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 30));

        propuestaTF.setBackground(new java.awt.Color(255, 255, 255));
        propuestaTF.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        propuestaTF.setForeground(new java.awt.Color(165, 165, 165));
        propuestaTF.setBorder(null);
        propuestaTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                propuestaTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                propuestaTFFocusLost(evt);
            }
        });
        propuestaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propuestaTFActionPerformed(evt);
            }
        });
        contenedor.add(propuestaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 360, 30));
        contenedor.add(sepPropuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 360, -1));
        contenedor.add(sepCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 360, -1));

        codigoTF.setBackground(new java.awt.Color(255, 255, 255));
        codigoTF.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        codigoTF.setForeground(new java.awt.Color(165, 165, 165));
        codigoTF.setBorder(null);
        codigoTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codigoTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigoTFFocusLost(evt);
            }
        });
        codigoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTFActionPerformed(evt);
            }
        });
        contenedor.add(codigoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 360, 30));

        modificarBP.setBackground(new java.awt.Color(118, 35, 47));
        modificarBP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modificarBP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        modificarBP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarBPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificarBPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificarBPMouseExited(evt);
            }
        });

        modificarBL.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        modificarBL.setForeground(new java.awt.Color(255, 255, 255));
        modificarBL.setText("Modificar");
        modificarBL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout modificarBPLayout = new javax.swing.GroupLayout(modificarBP);
        modificarBP.setLayout(modificarBPLayout);
        modificarBPLayout.setHorizontalGroup(
            modificarBPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarBPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modificarBL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        modificarBPLayout.setVerticalGroup(
            modificarBPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarBPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modificarBL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contenedor.add(modificarBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 90, -1));

        tablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Correlativas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMaterias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaMaterias.setFocusable(false);
        tablaMaterias.setRowHeight(25);
        tablaMaterias.setSelectionBackground(new java.awt.Color(118, 35, 47));
        tablaMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMateriasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaMaterias);
        if (tablaMaterias.getColumnModel().getColumnCount() > 0) {
            tablaMaterias.getColumnModel().getColumn(0).setResizable(false);
            tablaMaterias.getColumnModel().getColumn(1).setResizable(false);
            tablaMaterias.getColumnModel().getColumn(2).setResizable(false);
            tablaMaterias.getColumnModel().getColumn(2).setHeaderValue("Correlativas");
        }

        contenedor.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 430, 270));

        add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void tablaCorrelativasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCorrelativasMouseClicked
        
    }//GEN-LAST:event_tablaCorrelativasMouseClicked

    private void propuestaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propuestaTFActionPerformed
        modificarPlan();
    }//GEN-LAST:event_propuestaTFActionPerformed

    private void propuestaTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_propuestaTFFocusGained
        propuestaTF.setForeground(activo);
        propuestaTF.selectAll();
        sepPropuesta.setVisible(true);
    }//GEN-LAST:event_propuestaTFFocusGained

    private void propuestaTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_propuestaTFFocusLost
        if (propuestaTF.getText().equals("")) {
            try {
                propuestaTF.setText(PlanEstudiosManager.buscar(codPlanEstudios).getPropuesta());
            } catch (ManagementException e) {
            }
        }
        
        sepPropuesta.setVisible(false);
        propuestaTF.setForeground(inactivo);
    }//GEN-LAST:event_propuestaTFFocusLost

    private void codigoTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoTFFocusGained
        codigoTF.setForeground(activo);
        codigoTF.selectAll();
        sepCodigo.setVisible(true);
    }//GEN-LAST:event_codigoTFFocusGained

    private void codigoTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoTFFocusLost
        if (codigoTF.getText().equals("")) {
            codigoTF.setText(codPlanEstudios);
        }
        
        sepCodigo.setVisible(false);
        codigoTF.setForeground(inactivo);
    }//GEN-LAST:event_codigoTFFocusLost

    private void codigoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTFActionPerformed
        propuestaTF.requestFocus();
    }//GEN-LAST:event_codigoTFActionPerformed

    private void modificarBPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarBPMouseClicked
        modificarPlan();
    }//GEN-LAST:event_modificarBPMouseClicked

    private void modificarBPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarBPMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarBPMouseEntered

    private void modificarBPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarBPMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarBPMouseExited

    private void tablaMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMateriasMouseClicked
        llenarTablaCorrelativas((String) tablaMaterias.getValueAt(tablaMaterias.getSelectedRow(), 0));
    }//GEN-LAST:event_tablaMateriasMouseClicked

    private void codigoMateriaTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoMateriaTFFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoMateriaTFFocusGained

    private void codigoMateriaTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoMateriaTFFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoMateriaTFFocusLost

    private void codigoMateriaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoMateriaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoMateriaTFActionPerformed

    private void modificarMateriaBPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMateriaBPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarMateriaBPMouseClicked

    private void modificarMateriaBPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMateriaBPMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarMateriaBPMouseEntered

    private void modificarMateriaBPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMateriaBPMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarMateriaBPMouseExited

    private void nombreTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreTFFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTFFocusGained

    private void nombreTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreTFFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTFFocusLost

    private void nombreTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTFActionPerformed

    public void modificarMateria() {
        // TODO
    }
    
    public void modificarPlan() {
        try {
            PlanEstudiosManager.modificar(codPlanEstudios, new PlanEstudios(codigoTF.getText(), propuestaTF.getText()));
            
            JOptionPane.showMessageDialog(null, "Modificación realizada con éxito");
        } catch (ManagementException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void llenarTablaMaterias() {
        try {
            HashMap<String, Materia> materias = PlanEstudiosManager.getMateriasDePlan(codPlanEstudios);
            DefaultTableModel modelo = (DefaultTableModel) tablaMaterias.getModel();

            for (Materia materia : materias.values()) {
                modelo.addRow(new Object[]{materia.getCodigo(), materia.getNombre(), String.join(", ", materia.getCorrelativas())});
            }
        } catch (ManagementException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }
    
    public void llenarTablaCorrelativas(String codMateria) {
        try {
            LinkedList<Materia> materias = PlanEstudiosManager.getMaterias(codPlanEstudios, 
                    PlanEstudiosManager.getCodCorrelativas(codMateria, codPlanEstudios));
            DefaultTableModel modelo = (DefaultTableModel) tablaCorrelativas.getModel();

            modelo.setRowCount(0);
            
            for (Materia materia : materias) {
                modelo.addRow(new Object[]{materia.getCodigo(), materia.getNombre(), String.join(", ", materia.getCorrelativas())});
            }
        } catch (ManagementException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PrincipalL;
    private javax.swing.JLabel PrincipalL1;
    private javax.swing.JLabel PrincipalL2;
    private javax.swing.JLabel PrincipalL3;
    private javax.swing.JLabel PrincipalL4;
    private javax.swing.JLabel PrincipalL5;
    private javax.swing.JTextField codigoMateriaTF;
    private javax.swing.JTextField codigoTF;
    private javax.swing.JPanel contenedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel materiaP;
    private javax.swing.JLabel modificarBL;
    private javax.swing.JPanel modificarBP;
    private javax.swing.JLabel modificarMateriaBL;
    private javax.swing.JPanel modificarMateriaBP;
    private javax.swing.JTextField nombreTF;
    private javax.swing.JTextField propuestaTF;
    private javax.swing.JSeparator sepCodigo;
    private javax.swing.JSeparator sepCodigoMateria;
    private javax.swing.JSeparator sepNombre;
    private javax.swing.JSeparator sepPropuesta;
    private javax.swing.JTable tablaCorrelativas;
    private javax.swing.JTable tablaMaterias;
    // End of variables declaration//GEN-END:variables

}
