/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tp_maquina_is2.Interfaces.Paneles.NoDocente.ABMPlanDeEstudios;

import com.mycompany.tp_maquina_is2.Interfaces.Paneles.NoDocente.EstadisticasNoDocente;
import com.mycompany.tp_maquina_is2.Logica.Excepciones.ManagementException;
import com.mycompany.tp_maquina_is2.Logica.Managers.PlanEstudiosManager;
import com.mycompany.tp_maquina_is2.Logica.Transferencia.PlanEstudios;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ivanb
 */
public class SeleccionarPlan extends javax.swing.JPanel {

    private String operacion;

    /**
     * Creates new form ModificarPlan
     */
    public SeleccionarPlan(String operacion) {
        this.operacion = operacion;

        initComponents();

        if (operacion.equals("estadisticas")) {
            PrincipalL.setText("Seleccione el plan del que desea ver estadisticas");
        }

        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaExamenes = new javax.swing.JTable();
        PrincipalL = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedor.setBackground(new java.awt.Color(255, 255, 255));
        contenedor.setPreferredSize(new java.awt.Dimension(950, 500));
        contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaExamenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Porpuesta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaExamenes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TablaExamenes.setFocusable(false);
        TablaExamenes.setRowHeight(25);
        TablaExamenes.setSelectionBackground(new java.awt.Color(118, 35, 47));
        TablaExamenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaExamenesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaExamenes);

        contenedor.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 810, 330));

        PrincipalL.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        PrincipalL.setForeground(new java.awt.Color(165, 165, 165));
        PrincipalL.setText("Seleccione el Plan de Estudios que desea modificar");
        contenedor.add(PrincipalL, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 37));

        add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 670));
    }// </editor-fold>//GEN-END:initComponents

    private void TablaExamenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaExamenesMouseClicked
        String codPlan = (String) TablaExamenes.getValueAt(TablaExamenes.getSelectedRow(), 0);

        switch (operacion) {
            case "modificar":
                changePane(new ModificarPlan(codPlan));
                break;
            case "estadisticas":
                changePane(new EstadisticasNoDocente(codPlan));
        }

    }//GEN-LAST:event_TablaExamenesMouseClicked

    private void changePane(JPanel jPanel) {
        contenedor.setLayout(new java.awt.CardLayout());
        contenedor.removeAll();
        contenedor.add(jPanel);
        contenedor.revalidate();
        contenedor.repaint();
    }

    public void llenarTabla() {
        try {
            LinkedList<PlanEstudios> planes = PlanEstudiosManager.leer();
            DefaultTableModel modelo = (DefaultTableModel) TablaExamenes.getModel();
            for (PlanEstudios plan : planes) {
                modelo.addRow(new Object[]{plan.getCodigo(), plan.getPropuesta()});
            }
        } catch (ManagementException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PrincipalL;
    private javax.swing.JTable TablaExamenes;
    private javax.swing.JPanel contenedor;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
