/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package com.mycompany.tp_maquina_is2.Interfaces;

import com.mycompany.tp_maquina_is2.Interfaces.Paneles.Estudiante.InicioEstudiante;
import com.mycompany.tp_maquina_is2.Interfaces.Paneles.NoDocente.InicioNoDocente;
import com.mycompany.tp_maquina_is2.Logica.Transferencia.Estudiante;
import javax.swing.JPanel;

/**
 *
 * @author ivanb
 */
public class InicioPrincipal extends javax.swing.JPanel {

    private Estudiante user;
    private String codPlan;
    /** Creates new form Inicio */
    public InicioPrincipal(Estudiante user, String codPlan) {
        this.user = user;
        this.codPlan = codPlan;
        
        initComponents();
    }
    
    private void changePane(JPanel jPanel) {
        contenedor.setLayout(new java.awt.CardLayout());
        contenedor.removeAll();
        contenedor.add(jPanel);
        contenedor.revalidate();
        contenedor.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        estudianteBL = new javax.swing.JLabel();
        noDocenteBL = new javax.swing.JLabel();
        jLabelfondo = new javax.swing.JLabel();

        contenedor.setBackground(new java.awt.Color(255, 255, 255));
        contenedor.setPreferredSize(new java.awt.Dimension(950, 500));
        contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIENVENIDO");
        contenedor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 410, 110));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione una opción por favor:");
        contenedor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        estudianteBL.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        estudianteBL.setForeground(new java.awt.Color(255, 255, 255));
        estudianteBL.setText("ESTUDIANTE ");
        estudianteBL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        estudianteBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estudianteBLMouseClicked(evt);
            }
        });
        contenedor.add(estudianteBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 250, 70));

        noDocenteBL.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        noDocenteBL.setForeground(new java.awt.Color(255, 255, 255));
        noDocenteBL.setText("  NO DOCENTE");
        noDocenteBL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        noDocenteBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noDocenteBLMouseClicked(evt);
            }
        });
        contenedor.add(noDocenteBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 290, 70));

        jLabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inicio.jpg"))); // NOI18N
        jLabelfondo.setText("jLabel1");
        contenedor.add(jLabelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void estudianteBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estudianteBLMouseClicked
        changePane(new InicioEstudiante(user, codPlan));
    }//GEN-LAST:event_estudianteBLMouseClicked

    private void noDocenteBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noDocenteBLMouseClicked
        changePane(new InicioNoDocente());
    }//GEN-LAST:event_noDocenteBLMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel estudianteBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelfondo;
    private javax.swing.JLabel noDocenteBL;
    // End of variables declaration//GEN-END:variables

}
